repos:
-   repo: local
    hooks:
    -   id: dotnet-format
        name: dotnet-format
        language: system
        entry: dotnet tool run dotnet-format --folder -w --include
        types_or: ["c#"]
