version: '3.8'

services:
  grpc:
    image: arminvakil/dafny-server:latest
    ports:
      - "50051:50051"
    deploy:
      replicas: 50
      resources:
        reservations:
          cpus: '40'
      placement:
        constraints: [node.role != manager]
