version: "3.8"

services:
  dafny:
    image: arminvakil/dafny-server:latest
    deploy:
      replicas: 1600
    ports:
      - 50051:50051

networks:
  default:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 10.12.0.0/16
