# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import verifier_pb2 as verifier__pb2


class DafnyVerifierServiceStub(object):
    """Interface exported by the server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Verify = channel.unary_unary(
                '/DafnyExecutorServer.DafnyVerifierService/Verify',
                request_serializer=verifier__pb2.VerificationRequest.SerializeToString,
                response_deserializer=verifier__pb2.VerificationResponse.FromString,
                )


class DafnyVerifierServiceServicer(object):
    """Interface exported by the server.
    """

    def Verify(self, request, context):
        """Run Dafny on the given code and returns the output
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DafnyVerifierServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=verifier__pb2.VerificationRequest.FromString,
                    response_serializer=verifier__pb2.VerificationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DafnyExecutorServer.DafnyVerifierService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DafnyVerifierService(object):
    """Interface exported by the server.
    """

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/DafnyExecutorServer.DafnyVerifierService/Verify',
            verifier__pb2.VerificationRequest.SerializeToString,
            verifier__pb2.VerificationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
