# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x0b\x64\x61\x66nyserver\"D\n\x13VerificationRequest\x12\x11\n\x04\x63ode\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\targuments\x18\x02 \x03(\tB\x07\n\x05_code\":\n\x14VerificationResponse\x12\x15\n\x08response\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_response2^\n\x0b\x44\x61\x66nyServer\x12O\n\x06Verify\x12 .dafnyserver.VerificationRequest\x1a!.dafnyserver.VerificationResponse\"\x00\x62\x06proto3')



_VERIFICATIONREQUEST = DESCRIPTOR.message_types_by_name['VerificationRequest']
_VERIFICATIONRESPONSE = DESCRIPTOR.message_types_by_name['VerificationResponse']
VerificationRequest = _reflection.GeneratedProtocolMessageType('VerificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _VERIFICATIONREQUEST,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:dafnyserver.VerificationRequest)
  })
_sym_db.RegisterMessage(VerificationRequest)

VerificationResponse = _reflection.GeneratedProtocolMessageType('VerificationResponse', (_message.Message,), {
  'DESCRIPTOR' : _VERIFICATIONRESPONSE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:dafnyserver.VerificationResponse)
  })
_sym_db.RegisterMessage(VerificationResponse)

_DAFNYSERVER = DESCRIPTOR.services_by_name['DafnyServer']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VERIFICATIONREQUEST._serialized_start=30
  _VERIFICATIONREQUEST._serialized_end=98
  _VERIFICATIONRESPONSE._serialized_start=100
  _VERIFICATIONRESPONSE._serialized_end=158
  _DAFNYSERVER._serialized_start=160
  _DAFNYSERVER._serialized_end=254
# @@protoc_insertion_point(module_scope)
