name: Build DafnyRef.pdf

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
        ##os: [ macos-latest, ubuntu-18.04, ubuntu-latest ]

    steps:
    - name: OS
      run: echo ${{ runner.os }} ${{ matrix.os }}
    - uses: actions/setup-python@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1.9.0
      with:
        dotnet-version: 6.0.x
    - name: Checkout Dafny
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: dafny
    - name: Build Dafny
      run: dotnet build dafny/Source/Dafny.sln
    - name: Install latex pandoc - Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install texlive texlive-xetex
        wget https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-1-amd64.deb
        sudo dpkg -i *.deb
        rm -rf *.deb
      # apt-get has pandoc, but it is outdated
    - name: Extra linux packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install texlive-science
        sudo tlmgr init-usertree
        sudo tlmgr update --self
        sudo tlmgr install framed tcolorbox environ trimspaces unicode-math
        pandoc -v
        which latex || echo NOT FOUND latex
        which xelatex || echo NOT FOUND xelatex
        sudo gem install rouge
    - if: matrix.os != 'ubuntu-latest' && runner.os == 'Linux'
      run: |
        sudo apt-get install texlive-math-extra
        sudo tlmgr init-usertree
        sudo tlmgr update --self
        sudo tlmgr install framed tcolorbox environ trimspaces unicode-math
        pandoc -v
        which latex || echo NOT FOUND latex
        which xelatex || echo NOT FOUND xelatex
        sudo gem install rouge
    - name: Install latex pandoc - MacOS
      if: runner.os == 'MacOS'
      run: |
        brew install pandoc
        brew install --cask basictex
        eval "$(/usr/libexec/path_helper)"
        sudo tlmgr update --self
        sudo tlmgr install framed tcolorbox environ trimspaces unicode-math
        pandoc -v
        which latex || echo NOT FOUND latex
        which xelatex || echo NOT FOUND xelatex
        sudo gem install rouge
    - name: Build reference manual
      run: |
        eval "$(/usr/libexec/path_helper)"
        rm -f dafny/docs/DafnyRef/DafnyRef.pdf
        make -C dafny/docs/DafnyRef
    - name: Check
      run: ls -la dafny/docs/DafnyRef/DafnyRef.pdf
